[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "motor>=3.7.1",
    "pydantic[email]>=2.11.7",
    "sqlalchemy[asyncio]>=2.0.42",
]
